PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "WINONA has been this town's GYM LEADER\n"
	.string "for a good while now.\p"
	.string "She's been very popular with\n"
	.string "The kids around here.\p"
	.string "Ever since she came here they\n"
	.string "Have loved training with her.\p"
	.string "They are much better POKéMON TRAINERS\n"
	.string "Then when she first came here.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I battled WINONA once, but, whew,\n"
	.string "Her Piplup was something else.\p"
	.string "It's way to competitive!\p"
	.string "And her Skarmory was just\n"
	.string "Unfazed by my POKéMONS attacks.$"

