OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Hello young trainer!\n"
	.string "Welcome to my humble abode.\p"
	.string "I'm a collector of the rare and exotic,\n"
	.string "which makes these caverns a perfect\l"
	.string "place for me to stay.\p"
	.string "Whatever direction you go here,\n"
	.string "the seroundings will be completely.\l"
	.string "different from the last.\p"
	.string "It's a fascinating place to explore,\n"
	.string "but it can be dangerous too, so take care.\p"
	.string "I try to tend to the environment here,\n"
	.string "just as I would my own garden.\p"
	.string "But sometimes it feels like the\n"
	.string "this area is fighting against me.\p"
	.string "Everytime I finish cleaning up,\n"
	.string "the next day its already overgrown again.\p"
	.string "It can be a little unsettling,\n"
	.string "but this place is just to interesting\l"
	.string "to leave.\p"
	.string "If you see me around, don't be afraid\n"
	.string "to say hello. It can get a bit lonely.\l"
	.string "So it's a nice change of pace.$"

