PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Traveling is wonderful!\p"
	.string "But it's good to remember your\n"
	.string "roots and go home some times!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "But traveling around in this cold\n"
	.string "Weather really isn't for me.\p"
	.string "Maybe I could leave for a place \n"
	.string "With more tropical weather...\p"
	.string "I'd never even get homesick \n"
	.string "in that kind of weather!\p"
	.string "Man I guess I really should travel!$"

